# USAGE (ci.yml)
# jobs:
#   call_npm_package_build:
#     uses: szikszail/workflows/.github/workflows/npm-package-build.yml@main
#     with:
#       coverage_path: coverage/clover.xml
#       coverage_threshold_warning: 60
#       coverage_threshold_alert: 80
#       coverage_threshold_metric: branches
name: Building and testing NPM package
on:
  workflow_call:
    inputs:
      coverage_path:
        required: false
        default: 'coverage/clover.xml'
        type: string
      coverage_treshold_warning:
        required: false
        default: 60
        type: number
      coverage_treshold_alert:
        required: false
        default: 80
        type: number
      coverage_treshold_metric:
        required: false
        default: 'branches'
        type: string      
jobs:
  build_and_test:
    name: Build and test NPM package
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [lts/-1, lts/*, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Build and test
        run: npm run build
      - name: Monitor coverage
        if: ${{ always() }}
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: ${{ inputs.coverage_path }}
          threshold_alert: ${{ inputs.coverage_treshold_alert }}
          threshold_warning: ${{ inputs.coverage_treshold_warning }}
          threshold_metric: ${{ inputs.coverage_treshold_metric }}
